// Code generated by go-bindata.
// sources:
// src/mapping/asset/index.html
// src/mapping/asset/static/css/leaflet.css
// src/mapping/asset/static/images/layers-2x.png
// src/mapping/asset/static/images/layers.png
// src/mapping/asset/static/images/marker-icon-2x.png
// src/mapping/asset/static/images/marker-icon.png
// src/mapping/asset/static/images/marker-shadow.png
// src/mapping/asset/static/js/leaflet.js
// DO NOT EDIT!

package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// assetIndexHtml reads file data from disk. It returns an error on failure.
func assetIndexHtml() (*asset, error) {
	path := filepath.Join(rootDir, "asset/index.html")
	name := "asset/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetStaticCssLeafletCss reads file data from disk. It returns an error on failure.
func assetStaticCssLeafletCss() (*asset, error) {
	path := filepath.Join(rootDir, "asset/static/css/leaflet.css")
	name := "asset/static/css/leaflet.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetStaticImagesLayers2xPng reads file data from disk. It returns an error on failure.
func assetStaticImagesLayers2xPng() (*asset, error) {
	path := filepath.Join(rootDir, "asset/static/images/layers-2x.png")
	name := "asset/static/images/layers-2x.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetStaticImagesLayersPng reads file data from disk. It returns an error on failure.
func assetStaticImagesLayersPng() (*asset, error) {
	path := filepath.Join(rootDir, "asset/static/images/layers.png")
	name := "asset/static/images/layers.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetStaticImagesMarkerIcon2xPng reads file data from disk. It returns an error on failure.
func assetStaticImagesMarkerIcon2xPng() (*asset, error) {
	path := filepath.Join(rootDir, "asset/static/images/marker-icon-2x.png")
	name := "asset/static/images/marker-icon-2x.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetStaticImagesMarkerIconPng reads file data from disk. It returns an error on failure.
func assetStaticImagesMarkerIconPng() (*asset, error) {
	path := filepath.Join(rootDir, "asset/static/images/marker-icon.png")
	name := "asset/static/images/marker-icon.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetStaticImagesMarkerShadowPng reads file data from disk. It returns an error on failure.
func assetStaticImagesMarkerShadowPng() (*asset, error) {
	path := filepath.Join(rootDir, "asset/static/images/marker-shadow.png")
	name := "asset/static/images/marker-shadow.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// assetStaticJsLeafletJs reads file data from disk. It returns an error on failure.
func assetStaticJsLeafletJs() (*asset, error) {
	path := filepath.Join(rootDir, "asset/static/js/leaflet.js")
	name := "asset/static/js/leaflet.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"asset/index.html": assetIndexHtml,
	"asset/static/css/leaflet.css": assetStaticCssLeafletCss,
	"asset/static/images/layers-2x.png": assetStaticImagesLayers2xPng,
	"asset/static/images/layers.png": assetStaticImagesLayersPng,
	"asset/static/images/marker-icon-2x.png": assetStaticImagesMarkerIcon2xPng,
	"asset/static/images/marker-icon.png": assetStaticImagesMarkerIconPng,
	"asset/static/images/marker-shadow.png": assetStaticImagesMarkerShadowPng,
	"asset/static/js/leaflet.js": assetStaticJsLeafletJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"asset": &bintree{nil, map[string]*bintree{
		"index.html": &bintree{assetIndexHtml, map[string]*bintree{}},
		"static": &bintree{nil, map[string]*bintree{
			"css": &bintree{nil, map[string]*bintree{
				"leaflet.css": &bintree{assetStaticCssLeafletCss, map[string]*bintree{}},
			}},
			"images": &bintree{nil, map[string]*bintree{
				"layers-2x.png": &bintree{assetStaticImagesLayers2xPng, map[string]*bintree{}},
				"layers.png": &bintree{assetStaticImagesLayersPng, map[string]*bintree{}},
				"marker-icon-2x.png": &bintree{assetStaticImagesMarkerIcon2xPng, map[string]*bintree{}},
				"marker-icon.png": &bintree{assetStaticImagesMarkerIconPng, map[string]*bintree{}},
				"marker-shadow.png": &bintree{assetStaticImagesMarkerShadowPng, map[string]*bintree{}},
			}},
			"js": &bintree{nil, map[string]*bintree{
				"leaflet.js": &bintree{assetStaticJsLeafletJs, map[string]*bintree{}},
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

